# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.

# trigger:
# - master

pool:
      vmImage: 'ubuntu-latest'

# Add steps that build, run tests, deploy, and more:
# https://docs.microsoft.com/en-us/azure/azure-functions/functions-how-to-azure-devops?tabs=csharp
steps:
- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: restore
- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: build
    arguments: '--configuration Release'
    publishWebProjects: false
    modifyOutputPath: false
